name: Reorganize Repository Structure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  restructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Reorganize files
        run: |
          # Move problems from Easy, Medium, Hard to root (adjust this for each data structure folder)
          find . -type d -name "easy" -exec mv {}/* . \; -exec rm -r {} \;
          find . -type d -name "medium" -exec mv {}/* . \; -exec rm -r {} \;
          find . -type d -name "hard" -exec mv {}/* . \; -exec rm -r {} \;

          # Arrays and Hashing
          mkdir -p ArraysAndHashing
          mv -v 0001-two-sum ArraysAndHashing/ || true
          mv -v 0049-group-anagrams ArraysAndHashing/ || true
          mv -v 1365-how-many-numbers-are-smaller-than-the-current-number ArraysAndHashing/ || true

          # LinkedList
          mkdir -p LinkedList
          mv -v 0206-reverse-linked-list LinkedList/ || true
          mv -v 83-remove-duplicates-from-sorted-list LinkedList/ || true

          # Stacks
          mkdir -p Stacks
          mv -v 0020-valid-parentheses Stacks/ || true
          mv -v 144-binary-tree-preorder-traversal Stacks/ || true

          # Two Pointers
          mkdir -p TwoPointers
          mv -v 1678-goal-parser-interpretation TwoPointers/ || true
          mv -v 2836-neither-minimum-nor-maximum TwoPointers/ || true

          # Binary Search
          mkdir -p BinarySearch
          mv -v 783-search-in-a-binary-search-tree BinarySearch/ || true

          # Trees
          mkdir -p Trees
          mv -v 104-maximum-depth-of-binary-tree Trees/ || true
          mv -v 774-maximum-depth-of-n-ary-tree Trees/ || true

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatically reorganize repository structure"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
